# Generated by Django 6.1 on 2026-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin / Editor'), ('author', 'Author'), ('subscriber', 'Subscriber')], max_length=32, unique=True),
        ),
    ]
