# Generated by Django 6.1 on 2026-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin / Editor'), ('author', 'Author'), ('member', 'Member'), ('contributor', 'Contributor'), ('subscriber', 'Subscriber')], max_length=32, unique=True),
        ),
    ]
