# Generated by Django 6.1 on 2026-09-14 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberContributorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('other', 'Other')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('house_or_street', models.CharField(blank=True, max_length=255)),
                ('village_town_city', models.CharField(blank=True, max_length=150)),
                ('taluk', models.CharField(blank=True, max_length=150)),
                ('mandal', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('residential_status', models.CharField(blank=True, max_length=100)),
                ('citizenship', models.CharField(default='Indian', max_length=100)),
                ('educational_status', models.CharField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('below_poverty_line', models.BooleanField(default=False)),
                ('preferred_reporting_areas', models.JSONField(blank=True, default=list)),
                ('membership_category', models.CharField(blank=True, choices=[('member', 'Member'), ('contributor', 'Contributor'), ('reporter', 'Reporter'), ('media_staff', 'Media Staff'), ('editor', 'Editor'), ('bureau_chief', 'Bureau Chief'), ('camera_person', 'Camera Person'), ('volunteer', 'Volunteer'), ('district_coordinator', 'District Coordinator'), ('state_coordinator', 'State Coordinator'), ('other', 'Other')], max_length=50)),
                ('other_membership_category', models.CharField(blank=True, max_length=150)),
                ('selfie_photo', models.FileField(blank=True, null=True, upload_to='member-contributor/selfies/')),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='member-contributor/aadhaar/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='member-contributor/pan/')),
                ('identity_proof', models.FileField(blank=True, null=True, upload_to='member-contributor/identity-proof/')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='member-contributor/supporting-documents/')),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('communication_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_role', models.CharField(blank=True, choices=[('member', 'Member'), ('contributor', 'Contributor')], max_length=20, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_member_contributor_applications', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_member_contributor_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_contributor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
