# Generated by Django 6.1 on 2026-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membercontributorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberapplication',
            name='status',
        ),
    ]
