# Generated by Django 6.1 on 2026-09-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subscriberapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_super_admin', 'Super Super Admin'), ('super_admin', 'Super Admin'), ('super_author', 'Super Author'), ('admin', 'Admin / Editor'), ('author', 'Author'), ('member', 'Member'), ('contributor', 'Contributor'), ('subscriber', 'Subscriber')], max_length=32, unique=True),
        ),
    ]
