# Generated by Django 6.1 on 2026-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_number', models.CharField(blank=True, max_length=100)),
                ('publication_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(upload_to='emagazines/covers/')),
                ('pdf_file', models.FileField(upload_to='emagazines/pdfs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
