# Generated by Django 6.1 on 2026-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'media'},
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], default='image', max_length=16),
        ),
    ]
